name: "Nx Workspace Affected Apps"
description: "Determines the affected apps in an Nx workspace (monorepo)"
inputs:
    base:
        description: "SHA to compare to"
        default: "origin/master~1"
        required: false
    head:
        description: "SHA to compare from"
        default: "origin/master"
        required: false

outputs:
    affected_apps:
        description: "an array of affected app names"

runs:
    using: "node12"
    main: "dist/index.js"

branding:
    color: blue
    icon: "filter"
